/** @const {ShadowJS} */ var Buffer;
/** @const {ShadowJS} */ var File;
/** @const {ShadowJS} */ var FormData;
/** @const {ShadowJS} */ var NaN;
/** @const {ShadowJS} */ var XRegExp;
/** @const {ShadowJS} */ var alert;
/** @const {ShadowJS} */ var decodeURIComponent;
ShadowJS.prototype.NEGATIVE_INFINITY;
ShadowJS.prototype.NaN;
ShadowJS.prototype.POSITIVE_INFINITY;
ShadowJS.prototype.ceilingEntry;
ShadowJS.prototype.cleanup;
ShadowJS.prototype.createReadStream;
ShadowJS.prototype.equiv;
ShadowJS.prototype.existsSync;
ShadowJS.prototype.exit;
ShadowJS.prototype.finalize;
ShadowJS.prototype.floorEntry;
ShadowJS.prototype.fromArray;
ShadowJS.prototype.fromCharCode;
ShadowJS.prototype.getLength;
ShadowJS.prototype.getVerboseHandler;
ShadowJS.prototype.init;
ShadowJS.prototype.isComplete;
ShadowJS.prototype.keys;
ShadowJS.prototype.listen;
ShadowJS.prototype.lstatSync;
ShadowJS.prototype.parse;
ShadowJS.prototype.pipe;
ShadowJS.prototype.readFile;
ShadowJS.prototype.readFileSync;
ShadowJS.prototype.readdirSync;
ShadowJS.prototype.rep;
ShadowJS.prototype.setDomain;
ShadowJS.prototype.setPath;
ShadowJS.prototype.setPort;
ShadowJS.prototype.setProgressEventsEnabled;
ShadowJS.prototype.setQuery;
ShadowJS.prototype.setRequestTimeout;
ShadowJS.prototype.setScheme;
ShadowJS.prototype.setTimeoutInterval;
ShadowJS.prototype.setWithCredentials;
ShadowJS.prototype.stat;
ShadowJS.prototype.statSync;
ShadowJS.prototype.stringRep;
ShadowJS.prototype.stringify;
ShadowJS.prototype.unbounded_unshift;
ShadowJS.prototype.unlink;
ShadowJS.prototype.unlinkSync;
ShadowJS.prototype.writeFile;
ShadowJS.prototype.writeFileSync;