# Dockerfile para o serviço de autenticação
FROM python:3.7-slim

WORKDIR /auth

# Instalar dependências de compilação por conta do pacote vibora
RUN apt-get update && apt-get install -y \
    gcc \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

COPY auth/Pipfile Pipfile
RUN pip install pipenv
RUN pipenv install

COPY auth/. .

EXPOSE 8037

CMD ["pipenv", "run", "python", "src/server.py"]